name: personal_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.2.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: PostNoBillsJaffnaSemiBold
    fonts:
      - asset: assets/fonts/PostNoBillsJaffna-SemiBold.ttf
        weight: 600
  - family: PostNoBillsJaffnaExtraBold
    fonts:
      - asset: assets/fonts/PostNoBillsJaffna-ExtraBold.ttf
        weight: 600
